// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "window.h"

Fl_Double_Window *mat_win=(Fl_Double_Window *)0;

Fl_Box *mat_title=(Fl_Box *)0;

Fl_Value_Input *mat_x_1=(Fl_Value_Input *)0;

Fl_Value_Input *mat_x_2=(Fl_Value_Input *)0;

Fl_Value_Input *mat_x_3=(Fl_Value_Input *)0;

Fl_Value_Input *mat_y_1=(Fl_Value_Input *)0;

Fl_Value_Input *mat_y_2=(Fl_Value_Input *)0;

Fl_Value_Input *mat_y_3=(Fl_Value_Input *)0;

Fl_Value_Input *mat_z_1=(Fl_Value_Input *)0;

Fl_Value_Input *mat_z_2=(Fl_Value_Input *)0;

Fl_Value_Input *mat_z_3=(Fl_Value_Input *)0;

Fl_Button *mat_view_reset=(Fl_Button *)0;

Fl_Return_Button *mat_apply_button=(Fl_Return_Button *)0;

Fl_Light_Button *mat_keyed_mode=(Fl_Light_Button *)0;

/**
 Creates the GUI interaction window.
*/
Fl_Double_Window* make_main_win(Matrix33* mat, bool* r) {
  { mat_win = new Fl_Double_Window(305, 265, "Matrix Window");
    { mat_title = new Fl_Box(40, 10, 225, 25, "Manipulate Transform Matrix");
      mat_title->labeltype(FL_ENGRAVED_LABEL);
    } // Fl_Box* mat_title
    { mat_x_1 = new Fl_Value_Input(25, 60, 65, 25, "Scale X");
      mat_x_1->align(Fl_Align(FL_ALIGN_TOP));
    } // Fl_Value_Input* mat_x_1
    { mat_x_2 = new Fl_Value_Input(120, 60, 65, 25, "Skew X");
      mat_x_2->align(Fl_Align(FL_ALIGN_TOP));
    } // Fl_Value_Input* mat_x_2
    { mat_x_3 = new Fl_Value_Input(215, 60, 65, 25, "Trans. X");
      mat_x_3->align(Fl_Align(FL_ALIGN_TOP));
    } // Fl_Value_Input* mat_x_3
    { mat_y_1 = new Fl_Value_Input(25, 110, 65, 25, "Skew Y");
      mat_y_1->align(Fl_Align(FL_ALIGN_TOP));
    } // Fl_Value_Input* mat_y_1
    { mat_y_2 = new Fl_Value_Input(120, 110, 65, 25, "Scale Y");
      mat_y_2->align(Fl_Align(FL_ALIGN_TOP));
    } // Fl_Value_Input* mat_y_2
    { mat_y_3 = new Fl_Value_Input(215, 110, 65, 25, "Trans. Y");
      mat_y_3->align(Fl_Align(FL_ALIGN_TOP));
    } // Fl_Value_Input* mat_y_3
    { mat_z_1 = new Fl_Value_Input(25, 160, 65, 25, "Persp. X");
      mat_z_1->align(Fl_Align(FL_ALIGN_TOP));
    } // Fl_Value_Input* mat_z_1
    { mat_z_2 = new Fl_Value_Input(120, 160, 65, 25, "Persp. Y");
      mat_z_2->align(Fl_Align(FL_ALIGN_TOP));
    } // Fl_Value_Input* mat_z_2
    { mat_z_3 = new Fl_Value_Input(215, 160, 65, 25, "\"Trans. Z\"");
      mat_z_3->align(Fl_Align(FL_ALIGN_TOP));
    } // Fl_Value_Input* mat_z_3
    { mat_view_reset = new Fl_Button(25, 195, 85, 25, "Reset View");
      mat_view_reset->shortcut(0xff1b);
      mat_view_reset->callback((Fl_Callback*)cb_mat_view_reset, (void*)(r));
    } // Fl_Button* mat_view_reset
    { mat_apply_button = new Fl_Return_Button(130, 195, 150, 25, "Apply Transform");
      mat_apply_button->callback((Fl_Callback*)cb_mat_apply, (void*)(mat));
    } // Fl_Return_Button* mat_apply_button
    { mat_keyed_mode = new Fl_Light_Button(35, 230, 235, 25, "Switch to/from SDL2 Keys Mode");
      mat_keyed_mode->callback((Fl_Callback*)cb_keyed_mode);
    } // Fl_Light_Button* mat_keyed_mode
    mat_win->end();
  } // Fl_Double_Window* mat_win
  return mat_win;
}
