// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef window_h
#define window_h
#include <FL/Fl.H>
/**
 // Necessary for matrix work.
*/
#include "../mat.h"
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *mat_win;
#include <FL/Fl_Box.H>
extern Fl_Box *mat_title;
#include <FL/Fl_Value_Input.H>
extern Fl_Value_Input *mat_x_1;
extern Fl_Value_Input *mat_x_2;
extern Fl_Value_Input *mat_x_3;
extern Fl_Value_Input *mat_y_1;
extern Fl_Value_Input *mat_y_2;
extern Fl_Value_Input *mat_y_3;
extern Fl_Value_Input *mat_z_1;
extern Fl_Value_Input *mat_z_2;
extern Fl_Value_Input *mat_z_3;
#include <FL/Fl_Button.H>
extern void cb_mat_view_reset(Fl_Button*, bool*);
extern Fl_Button *mat_view_reset;
#include <FL/Fl_Return_Button.H>
extern void cb_mat_apply(Fl_Return_Button*, Matrix33*);
extern Fl_Return_Button *mat_apply_button;
#include <FL/Fl_Light_Button.H>
extern void cb_keyed_mode(Fl_Light_Button*, void*);
extern Fl_Light_Button *mat_keyed_mode;
Fl_Double_Window* make_main_win(Matrix33* mat, bool* r);
#endif
